apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: vaccination-app
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==  # base64 encoded value of 'root'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: vaccination-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: mysql-secret
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc  # Reference to a PersistentVolumeClaim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: vaccination-app
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
