apiVersion: v1
kind: Secret
metadata:
  name: phpmyadmin-secret
  namespace: vaccination-app
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==  # base64 encoded value of 'root'
  PMA_USER: cm9vdA==
  PMA_PASSWORD: cm9vdA==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phpmyadmin-config
  namespace: vaccination-app
data:
  PMA_HOST: "mysql"  # The hostname of the MySQL service
  PMA_PORT: "3306"   # The port on which MySQL is running
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: vaccination-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: phpmyadmin-config
            - secretRef:
                name: phpmyadmin-secret
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: vaccination-app
spec:
  type: ClusterIP  # Change to ClusterIP if you want internal access only
  ports:
    - port: 8081
      targetPort: 80
  selector:
    app: phpmyadmin
